apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bn67xi1kq-go
  janus-idp.io/tekton: bn67xi1kq-go
  backstage.io/kubernetes-id: bn67xi1kq-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bn67xi1kq-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
